### ISSUE TITLE
Install ok but weird results

### ISSUE THREAD

**Issue by pezou45** [BenHerbst/Dalaix#1]
Hi, i tried to install dalaix after failing to make work dalai. In both case, install is ok, i have no errors. But when i try the interface, i got weird results like this:

![dalai](https://user-images.githubusercontent.com/128334480/228537253-b2781eaf-7a22-4738-a1d7-8f4dad4735b7.png)
![dalai2](https://user-images.githubusercontent.com/128334480/228537276-a18962fe-7b4e-49e8-b145-c1c603da3ed3.png)
![dalai3](https://user-images.githubusercontent.com/128334480/228542028-67294763-c027-4965-95ca-eba827263172.png)

I'm not sure but isn't that debug results ? Cause i only get that, no matter what the prompt is and debug isn't checked (got same thing if it's checked)

**Comment by pezou45** [comment]
I talked to someone having the same problem and i'm the third person he knows has the problem and using a french machine. 
Can be related somehow ?

**Comment by OnlineNewsVentures** [comment]
I am having the exact issue in an W10Pro. It's frustration incarnate

**Comment by BenHerbst** [comment]
Wierd, I never experienced that issue.
Is it just related to Dalaix or do you get the same problem with installing Dalai without my app?
Then it's a problem with Dalai and you should file a GitHub issue there at https://github.com/cocktailpeanut/dalai/issues

**Comment by BenHerbst** [comment]
Seems to be related to Dalai and not Dalaix
