### ISSUE TITLE
Drive Selection

### ISSUE THREAD

**Issue by Sventzu** [BenHerbst/Dalaix#5]
Got it to work on my laptop, however I need to move it from C drive to D Drive. Is the an option to select drives?
Would be  #handy./
Cheers

**Comment by BenHerbst** [comment]
Currently, no option exists, but you should be able to just move the directory around and then update the taskbar links, but I can add an option for it in next release

**Comment by BenHerbst** [comment]
I think about an option like: Install directory. You can then install it anywhere, even in sub directories etc.

**Comment by BenHerbst** [comment]
Closed it with the new release: https://github.com/BenHerbst/Dalaix/releases/tag/v1.1.0
Have fun with it!

**Comment by Sventzu** [comment]
Thanks mate. I will give it a try and let you know how it goes

**Comment by viktor02** [comment]
It clogged my C drive, even though I chose a different drive. Is there any way to stay within the drive I specified?
Btw, Why install Visual studio, even outdated? Even though I already have all the dependencies. Or at least install only the build sdk? Why do not use prebuild binary for llama? 
![изображение](https://user-images.githubusercontent.com/19672960/229914845-4e667e8a-5a93-410c-b363-9af053b938f2.png)

**Comment by viktor02** [comment]
![изображение](https://user-images.githubusercontent.com/19672960/229918247-ef0f9729-31b2-47f7-ae43-324cfb7f852c.png)
0 bytes free, I think it's a success.

![изображение](https://user-images.githubusercontent.com/19672960/229918188-c6963124-5bf8-499b-873f-352dd429b218.png)

**Comment by BenHerbst** [comment]
> It clogged my C drive, even though I chose a different drive. Is there any way to stay within the drive I specified? Btw, Why install Visual studio, even outdated? Even though I already have all the dependencies. Or at least install only the build sdk? Why do not use prebuild binary for llama? ![изображение](https://user-images.githubusercontent.com/19672960/229914845-4e667e8a-5a93-410c-b363-9af053b938f2.png)

This uses Dalai. Dalai uses Visual Studio and no binary, this app here is just kinda an installer for Dalai
