### ISSUE TITLE
'dalai' is not recognized

### ISSUE THREAD

**Issue by Simmarith** [BenHerbst/Dalaix#7]
Ran the setup from the release, installed alpaca 7B, tried to run start.bat in an admin powershell. This is what I got out:
```ps
C:\Dalai>cd C:\Dalai\dalai   && PowerShell -Command "Add-Type -AssemblyName PresentationFramework;[System.Windows.MessageBox]::Show('Starting Dalai server ...', 'Dalaix by Ben Herbst')"   && npx dalai serve
OK
'dalai' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by BenHerbst** [comment]
Try cd C:\Dalai\dalai and type npm install. This installs dalai manually, give me feedback afterwards!

**Comment by Simmarith** [comment]
> Try cd C:\Dalai\dalai and type npm install. This installs dalai manually, give me feedback afterwards!

Sadly that didn't change anything at all - I `npm i`'d in there and then restarted my powershell. Still the same output.

**Comment by BenHerbst** [comment]
What happens when you open cmd not powershell in C:\Dalai\dalai and write npx dalai serve?

It seems that you already had some npm installed before or so and now they are maybe conflicting or something. It is quite hard for me to test Dalaix as the installation takes so long and I have to use Virtual Machines yk and it wont run on all windows depending on what you installed before cause Dalaix installs own npm etc. So as Dalai requires specific versions and then it may break

**Comment by Simmarith** [comment]
Sooo

I've tried in regular cmd (admin and non-admin) - Same result

I've tried uninstalling node, rebooting, rerunning dalaix and running the start.sh - apparently it is not installing its own node/npm

Then I've tried installing node again, running the start.bat - no avail

Then I've `npm i`'d the c:/dalai/dalai folder and tried both the start.bat and `npx dalai serve` - still nothing

Just a bunch of 

'dalai' is not recognized as an internal or external command,
operable program or batch file.

**Comment by BenHerbst** [comment]
Maybe this is more a problem with Dalai and not Dalaix, but idk, at me its working in the VMs and also others reported it is working, so i dont really know, maybe search in the Dalai issues too as this could be Dalai related and not Dalaix

**Comment by Simmarith** [comment]
So I've sorta gotten it to work by `npm i dalai` IN `C:\Dalai\dalai` (so we're basically adding dalai as a dependency to itself I guess?) and then running `npx dalai alpaca install 7B` and `npx dalai serve` in there. I don't know which of the several dalai installations we're using right now, but it's installing and picking up the model from the home dir and everything.

So this is probably an issue with Dalai itself and I guess this Issue can sit here as a workaround for people to get at least something to run.
