### ISSUE TITLE
No response after using Start dalai

### ISSUE THREAD

**Issue by laoxiongshiye** [BenHerbst/Dalaix#8]
System win10, python3.10, nodejs 18, vs2019, git+git lfs

after installing model prompts in Dalaix successfully, running Start Dalai without any prompts and reactions

**Comment by laoxiongshiye** [comment]
BTW, I choose Alpaca 13B Model, there is only "start.bat" and "stop.bat" in selected install directory.

**Comment by BenHerbst** [comment]
Start Dalaix from console and send me the console log please

**Comment by atoms55** [comment]
Try this fix, look for something like C:\Users\User\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js
I had the same issue and this fixed it for me.

https://github.com/cocktailpeanut/dalai/issues/421

**Comment by BenHerbst** [comment]
Seems to be an issue with Dalai then, so not directly related to Dalaix, so I close this issue here now and this bug continues to be tracked in the Dalai Github Issues not the Dalaix ones
